apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    service: grafana
  name: grafana
spec:
  ports:
  - name: "grafana"
    port: 3000
    targetPort: 3000
  selector:
    service: grafana
status:
  loadBalancer: {}
