apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    service: kava-prometheus
  name: kava-prometheus
spec:
  ports:
  - name: "kava-prometheus"
    port: 9040
    targetPort: 9040
  selector:
    service: kava-prometheus
