version: '3'

services:
  docker-cosmos:
    container_name: cosmos-mainnet
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - MONIKER=NodeName
      - CHAIN_ID=cosmoshub-2
      - GENESIS_URL=https://raw.githubusercontent.com/cosmos/launch/master/genesis.json
      - SEEDS=207737c436edf4778b983ac067fb4b8048c42c9e@35.196.175.11:26656
      - BOOTSTRAP=FALSE
      # - ADDR_BOOK_STRICT=false
      # - CACHE_SIZE=10000
    restart: always
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317" # for rest-server
    volumes:
      - cosmos-mainnet-data:/.gaiad
volumes:
  cosmos-mainnet-data:

