apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: iris-prometheus
  name: iris-prometheus
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      service: iris-prometheus
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: iris-prometheus
    spec:
      containers:
        - name: iris-prometheus
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cosmos-config
          image: ryanhendricks/docker-prometheus:latest
          resources: {}
      restartPolicy: Always
