apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iris-001
  namespace: default
spec:
  # storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
