apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: iris-001
    protocol: iris
  name: iris-001
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      service: iris-001
  template:
    metadata:
      labels:
        service: iris-001
        protocol: iris
    spec:
      containers:
        - name: iris-001
          image: ryanhendricks/docker-irisnet:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: iris-config
          volumeMounts:
            - mountPath: /.iris
              name: iris-001
          resources:
            requests:
              cpu: 1500m
              memory: 4Gi
            limits:
              cpu: 1800m
              memory: 6Gi
      restartPolicy: Always
      volumes:
        - name: iris-001
          persistentVolumeClaim:
            claimName: iris-001
