apiVersion: v1
kind: Service
metadata:
  name: regen-001
  namespace: default
  labels:
    service: regen-001
spec:
  ports:
  - name: "p2p-regen"
    port: 56656
    targetPort: 56656
  - name: "rpc-regen"
    port: 56657
    targetPort: 56657
  - name: "abci-regen"
    port: 56658
    targetPort: 56658
  - name: "metrics-regen"
    port: 56660
    targetPort: 56660
  - name: "lcd-regen"
    port: 5317
    targetPort: 5317
  selector:
    service: regen-001