apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: kava-001
    service: kava-001
  name: kava-001
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: kava-001
  template:
    metadata:
      labels:
        app: kava-001
        service: kava-001
    spec:
      containers:
        - name: kava-001
          image: ryanhendricks/docker-kava:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: kava-config
          volumeMounts:
            - mountPath: /.kvd
              name: kava-001
          resources:
            requests:
              cpu: 800m
              memory: 2Gi
            limits:
              cpu: 1200m
              memory: 3Gi
      restartPolicy: Always
      volumes:
        - name: kava-001
          persistentVolumeClaim:
            claimName: kava-001
