apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: kava-001
    service: kava-001
  name: kava-001
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: kava-001
  template:
    metadata:
      labels:
        app: kava-001
        service: kava-001
    spec:
      containers:
      - name: kava-001
        image: ryanhendricks/docker-kava:latest
        imagePullPolicy: Always
        env:
          - name: MONIKER
            value: "Kava-Test-2000"
          - name: CHAIN_ID
            value: kava-testnet-2000
          - name: GENESIS_URL
            value: https://raw.githubusercontent.com/Kava-Labs/kava-testnets/master/2000/genesis.json
          - name: SEEDS
            value: "01257db868b80e97ab2500d6dbd4e363ea66bce9@167.71.82.149:26656,029bf9259159299abbce18f80d7b962f43c02cd8@52.15.93.51:26656"
          - name: PERSISTENT_PEERS
            value: "01257db868b80e97ab2500d6dbd4e363ea66bce9@167.71.82.149:26656,029bf9259159299abbce18f80d7b962f43c02cd8@52.15.93.51:26656"
          - name: KVD_HOME
            value: /.kava
          - name: ADDR_BOOK_STRICT
            value: "false"
          - name: CACHE_SIZE
            value: "10000"
          - name: PROMETHEUS
            value: "true"
          - name: PROMETHEUS_LISTEN_ADDR
            value: "46660"
          - name: MAX_OPEN_CONNECTIONS
            value: "10"
          - name: BOOTSTRAP
            value: "FALSE"
          - name: LCD_PORT
            value: "4317"
          - name: RPC_LADDR_PORT
            value: "46657"
          - name: CORS_ALLOWED_ORIGINS
            value: "*"
          - name: CONNECTIONS_LADDR_PORT
            value: "46656"
          - name: PROXY_APP_PORT
            value: "46658"
        volumeMounts:
          - mountPath: /.kava
            name: kava-001
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
      restartPolicy: Always
      volumes:
      - name: kava-001
        persistentVolumeClaim:
          claimName: kava-001