version: 2
jobs:
  build-cosmos:
    environment:
      IMAGE_NAME: ryanhendricks/docker-cosmos
      VERSION: v0.34.7
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest ./dockerfiles/docker-cosmos
      - run:
          name: tag image
          command: docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION-$CIRCLE_SHA1
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest && docker push $IMAGE_NAME:$VERSION-$CIRCLE_SHA1
  build-cosmos-testnet:
    environment:
      IMAGE_NAME: ryanhendricks/docker-cosmos
      VERSION: v2.0.2
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:testnet ./dockerfiles/docker-cosmos -f ./dockerfiles/docker-cosmos/Dockerfile-testnet
      - run:
          name: tag image
          command: docker tag $IMAGE_NAME:testnet $IMAGE_NAME:testnet-$CIRCLE_SHA1
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:testnet && docker push $IMAGE_NAME:testnet-$CIRCLE_SHA1
  build-irisnet:
    environment:
      IMAGE_NAME: ryanhendricks/docker-irisnet
      VERSION: v0.16.0
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest ./dockerfiles/docker-irisnet
      - run:
          name: tag image
          command: docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest && docker push $IMAGE_NAME:$VERSION
  build-terra:
    environment:
      IMAGE_NAME: ryanhendricks/docker-terra
      VERSION: v0.2.6
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest ./dockerfiles/docker-irisnet
      - run:
          name: tag image
          command: docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest && docker push $IMAGE_NAME:$VERSION
workflows:
  version: 2
  build-master:
    jobs:
      - build-cosmos:
          filters:
            branches:
              only: master
      - build-cosmos-testnet:
          filters:
            branches:
              only: master
      - build-irisnet:
          filters:
            branches:
              only: master
      - build-terra:
          filters:
            branches:
              only: master
