apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: terra-prometheus
  name: terra-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      service: terra-prometheus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: terra-prometheus
    spec:
      containers:
        - name: terra-prometheus
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: terra-config
          image: ryanhendricks/docker-prometheus:latest
          resources: {}
      restartPolicy: Always
