apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: terra-prometheus
  name: terra-prometheus
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: terra-prometheus
    spec:
      containers:
      - name: terra-prometheus
        imagePullPolicy: Always
        env:
          - name: PROMETHEUS_L_ADDR
            value: "0.0.0.0"
          - name: PROMETHEUS_PORT
            value: "9060"
          - name: JOBNAME
            value: "terra-001"
          - name: TARGET_HOST
            value: "terra-001"
          - name: TARGET_PORT
            value: "26650"
          - name: INSTANCE
            value: "terra-001"
        image: ryanhendricks/docker-prometheus:latest
        resources: {}
      restartPolicy: Always
