apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    service: terra-prometheus
  name: terra-prometheus
spec:
  ports:
  - name: "terra-prometheus"
    port: 9050
    targetPort: 9050
  selector:
    service: terra-prometheus
