apiVersion: v1
kind: Service
metadata:
  name: terra-001
  namespace: default
  labels:
    service: terra-001
spec:
  ports:
  - name: "p2p-terra"
    port: 56656
    targetPort: 56656
  - name: "rpc-terra"
    port: 56657
    targetPort: 56657
  - name: "abci-terra"
    port: 56658
    targetPort: 56658
  - name: "metrics-terra"
    port: 56660
    targetPort: 56660
  - name: "lcd-terra"
    port: 5317
    targetPort: 5317
  selector:
    service: terra-001