apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terra-001
  namespace: default
spec:
  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
