apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    service: iris-prometheus
  name: iris-prometheus
spec:
  ports:
  - name: "iris-prometheus"
    port: 9030
    targetPort: 9030
  selector:
    service: iris-prometheus
