apiVersion: v1
kind: Service
metadata:
  name: kava-001
  namespace: default
  labels:
    service: kava-001
spec:
  ports:
  - name: "p2p-kava"
    port: 46656
    targetPort: 46656
  - name: "rpc-kava"
    port: 46657
    targetPort: 46657
  - name: "abci-kava"
    port: 46658
    targetPort: 46658
  - name: "metrics-kava"
    port: 46660
    targetPort: 46660
  - name: "lcd-kava"
    port: 4317
    targetPort: 4317
  selector:
    service: kava-001