apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosmos-001
  namespace: default
spec:
  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
status: {}
