apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: cosmos-001
    app: cosmos-001
  name: cosmos-001
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: cosmos-001
  template:
    metadata:
      labels:
        app: cosmos-001
        service: cosmos-001
    spec:
      containers:
        - name: cosmos-001
          image: ryanhendricks/docker-cosmos:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cosmos-config
          volumeMounts:
            - mountPath: /.gaiad
              name: cosmos-001
          resources:
            requests:
              cpu: 400m
              memory: 2Gi
            limits:
              cpu: 1200m
              memory: 3Gi
      restartPolicy: Always
      volumes:
        - name: cosmos-001
          persistentVolumeClaim:
            claimName: cosmos-001
