apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    service: cosmos-prometheus
  name: cosmos-prometheus
spec:
  ports:
    - name: "cosmos-prometheus"
      port: 9020
      targetPort: 9020
  selector:
    service: cosmos-prometheus
