apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: cosmos-prometheus
  name: cosmos-prometheus
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: cosmos-prometheus
    spec:
      containers:
        - name: cosmos-prometheus
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cosmos-config
          image: ryanhendricks/docker-prometheus:latest
          resources: {}
      restartPolicy: Always
