apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    service: regen-prometheus
  name: regen-prometheus
spec:
  ports:
  - name: "regen-prometheus"
    port: 9050
    targetPort: 9050
  selector:
    service: regen-prometheus
