apiVersion: v1
kind: Service
metadata:
  name: cosmos-001
  namespace: default
  labels:
    service: cosmos-001
spec:
  ports:
    - name: "p2p-cosmos"
      port: 26656
      targetPort: 26656
    - name: "rpc-cosmos"
      port: 26657
      targetPort: 26657
    - name: "abci-cosmos"
      port: 26658
      targetPort: 26658
    - name: "metrics-cosmos"
      port: 26660
      targetPort: 26660
    - name: "lcd-cosmos"
      port: 1317
      targetPort: 1317
  selector:
    service: cosmos-001
